// Mocks generated by Mockito 5.3.2 from annotations
// in github_issues/test/domain/use_case/get_issues_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:github_issues/domain/entity/issue_entity.dart' as _i2;
import 'package:github_issues/domain/repository/issues_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIssueEntity_0 extends _i1.SmartFake implements _i2.IssueEntity {
  _FakeIssueEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IssuesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIssuesRepository extends _i1.Mock implements _i3.IssuesRepository {
  MockIssuesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.IssueEntity>> getIssues() => (super.noSuchMethod(
        Invocation.method(
          #getIssues,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.IssueEntity>>.value(<_i2.IssueEntity>[]),
      ) as _i4.Future<List<_i2.IssueEntity>>);
  @override
  _i4.Future<_i2.IssueEntity> getIssue(int? number) => (super.noSuchMethod(
        Invocation.method(
          #getIssue,
          [number],
        ),
        returnValue: _i4.Future<_i2.IssueEntity>.value(_FakeIssueEntity_0(
          this,
          Invocation.method(
            #getIssue,
            [number],
          ),
        )),
      ) as _i4.Future<_i2.IssueEntity>);
  @override
  dynamic setVisitedIssues(List<String>? issues) =>
      super.noSuchMethod(Invocation.method(
        #setVisitedIssues,
        [issues],
      ));
  @override
  _i4.Future<List<String>> getVisitedIssues() => (super.noSuchMethod(
        Invocation.method(
          #getVisitedIssues,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);
}
